import type { RigSpec } from "../Rig";

/**
 * Per-character appearance data. Story, weapons, personality and home spots
 * live in `docs/DESIGN.md` — do not reshape silhouettes without an explicit ask.
 *
 * Personality / utility weights will hang off this type later as plain numbers;
 * the AI should only ever read data from here, not hard-code character names.
 *
 * Spec numbers are edited by the in-game rig tuner (press `~`), exported with
 * 导出存档, and pasted back over the blocks below from the bundle's
 * `profiles.ts.txt`. The piece lists are written out in full rather than
 * generated by the `fringe`/`pair` helpers, because once a fringe has been
 * nudged strand by strand in the tuner there is no formula left to describe it.
 */
export interface CharacterProfile {
  id: string;
  displayName: string;
  spec: Partial<RigSpec>;
  /**
   * Fallback spawn if furniture has no preferred spot for this id.
   * Runtime prefers `Furniture.preferredSpotFor(id)` (see main.ts).
   */
  spawn: { x: number; z: number };
}

export const profiles: CharacterProfile[] = [
  {
    id: "heath",
    displayName: "Heath",
    // Appearance only — lore/weapons/home: docs/DESIGN.md (sniper, naps on sofa).
    // Tallest. Black suit, white collar, brown hair in a 3:7 side part with a
    // long high ponytail.
    spec: {
      scale: 1.06,
      tailLength: 0.58,
      tailThickness: 0.08,
      tailAnchorY: 0.62,
      tailTilt: 0.72,
      hairShade: 0x452c1e,
      pieces: [
        { shape: "disc", color: 0x24242c, azimuth: 0.34, elevation: 0.165, lift: 0.004, width: 0.07, length: 0.085, taper: 0.7, skew: 0, bend: 0, pitch: 0, spin: 0, thickness: 0.012, pad: 1.4, note: "眼睛" },
        { shape: "disc", color: 0x24242c, azimuth: -0.34, elevation: 0.165, lift: 0.004, width: 0.07, length: 0.085, taper: 0.7, skew: 0, bend: 0, pitch: 0, spin: 0, thickness: 0.012, pad: 1.4, note: "眼睛" },
        { shape: "disc", color: 0xd9a97f, azimuth: 0.74, elevation: -0.2, lift: 0.003, width: 0.07, length: 0.045, taper: 0.7, skew: 0, bend: 0, pitch: 0, spin: 0, thickness: 0.01, pad: 1.4, note: "腮红" },
        { shape: "disc", color: 0xd9a97f, azimuth: -0.74, elevation: -0.2, lift: 0.003, width: 0.07, length: 0.045, taper: 0.7, skew: 0, bend: 0, pitch: 0, spin: 0, thickness: 0.01, pad: 1.4, note: "腮红" },
        { shape: "lock", color: 0x5b3d2b, azimuth: -0.15, elevation: 0.82, lift: 0, width: 0.13, length: 0.2, taper: 0.55, skew: -0.05, bend: -0.042, pitch: 0.1, spin: 0, thickness: 0.035, pad: 1.4 },
        { shape: "lock", color: 0x5b3d2b, azimuth: 0.317, elevation: 0.82, lift: 0.004, width: 0.13, length: 0.177, taper: 0.55, skew: -0.05, bend: 0.089, pitch: 0.1, spin: 0, thickness: 0.035, pad: 1.4 },
        { shape: "lock", color: 0x5b3d2b, azimuth: 0.783, elevation: 0.82, lift: 0.008, width: 0.13, length: 0.153, taper: 0.55, skew: -0.05, bend: 0.219, pitch: 0.1, spin: 0, thickness: 0.035, pad: 1.4 },
        { shape: "lock", color: 0x5b3d2b, azimuth: 1.25, elevation: 0.82, lift: 0.012, width: 0.13, length: 0.13, taper: 0.55, skew: -0.05, bend: 0.35, pitch: 0.1, spin: 0, thickness: 0.035, pad: 1.4 },
        { shape: "lock", color: 0x5b3d2b, azimuth: -1.15, elevation: 0.82, lift: 0, width: 0.12, length: 0.13, taper: 0.55, skew: 0.03, bend: -0.322, pitch: 0.1, spin: 0, thickness: 0.035, pad: 1.4 },
        { shape: "lock", color: 0x5b3d2b, azimuth: -0.3, elevation: 0.82, lift: 0.004, width: 0.12, length: 0.13, taper: 0.55, skew: 0.03, bend: -0.084, pitch: 0.1, spin: 0, thickness: 0.035, pad: 1.4 },
        { shape: "lock", color: 0x5b3d2b, azimuth: 1.45, elevation: 0.16, lift: 0, width: 0.1, length: 0.26, taper: 0.35, skew: 0, bend: 0, pitch: 0.04, spin: 0, thickness: 0.035, pad: 1.4, note: "鬓发" },
        { shape: "lock", color: 0x5b3d2b, azimuth: -1.45, elevation: 0.16, lift: 0, width: 0.1, length: 0.26, taper: 0.35, skew: 0, bend: 0, pitch: 0.04, spin: 0, thickness: 0.035, pad: 1.4, note: "鬓发" },
      ],
    },
    spawn: { x: -2.0, z: -0.9 },
  },
  {
    id: "honglu",
    displayName: "Honglu",
    // Appearance only — lore/weapons/home: docs/DESIGN.md (boss; pistol + knife).
    // Dark coat, almost no contrast. The half-fringe over one eye and a teal
    // hair tie as the single spot of colour.
    spec: {
      capDepth: 1.05,
      tailLength: 0.3,
      tailAnchorY: 0.68,
      tailTilt: 0.95,
      hair: 0x342c4c,
      hairShade: 0x241e36,
      hairTie: 0x4fb3a5,
      body: 0x1e1e26,
      hem: 0x24242c,
      accent: 0x33333d,
      pieces: [
        { shape: "disc", color: 0x24242c, azimuth: 0.34, elevation: 0.165, lift: 0.004, width: 0.07, length: 0.075, taper: 0.7, skew: 0, bend: 0, pitch: 0, spin: 0, thickness: 0.012, pad: 1.4, note: "眼睛" },
        { shape: "disc", color: 0x24242c, azimuth: -0.34, elevation: 0.165, lift: 0.004, width: 0.07, length: 0.075, taper: 0.7, skew: 0, bend: 0, pitch: 0, spin: 0, thickness: 0.012, pad: 1.4, note: "眼睛" },
        { shape: "disc", color: 0xd9a97f, azimuth: 0.74, elevation: -0.2, lift: 0.003, width: 0.07, length: 0.045, taper: 0.7, skew: 0, bend: 0, pitch: 0, spin: 0, thickness: 0.01, pad: 1.4, note: "腮红" },
        { shape: "disc", color: 0xd9a97f, azimuth: -0.74, elevation: -0.2, lift: 0.003, width: 0.07, length: 0.045, taper: 0.7, skew: 0, bend: 0, pitch: 0, spin: 0, thickness: 0.01, pad: 1.4, note: "腮红" },
        { shape: "lock", color: 0x342c4c, azimuth: -1.2, elevation: 0.82, lift: 0, width: 0.13, length: 0.26, taper: 0.55, skew: 0.04, bend: -0.336, pitch: 0.1, spin: 0, thickness: 0.035, pad: 1.4 },
        { shape: "lock", color: 0x342c4c, azimuth: -0.767, elevation: 0.82, lift: 0.004, width: 0.13, length: 0.221, taper: 0.55, skew: 0.04, bend: -0.215, pitch: 0.1, spin: 0, thickness: 0.035, pad: 1.4 },
        { shape: "lock", color: 0x342c4c, azimuth: -0.333, elevation: 0.82, lift: 0.008, width: 0.13, length: 0.182, taper: 0.55, skew: 0.04, bend: -0.093, pitch: 0.1, spin: 0, thickness: 0.035, pad: 1.4 },
        { shape: "lock", color: 0x342c4c, azimuth: 0.1, elevation: 0.82, lift: 0.012, width: 0.13, length: 0.143, taper: 0.55, skew: 0.04, bend: 0.028, pitch: 0.1, spin: 0, thickness: 0.035, pad: 1.4 },
        { shape: "lock", color: 0x342c4c, azimuth: 0.45, elevation: 0.82, lift: 0, width: 0.11, length: 0.11, taper: 0.55, skew: 0, bend: 0.126, pitch: 0.1, spin: 0, thickness: 0.035, pad: 1.4 },
        { shape: "lock", color: 0x342c4c, azimuth: 1.15, elevation: 0.82, lift: 0.004, width: 0.11, length: 0.11, taper: 0.55, skew: 0, bend: 0.322, pitch: 0.1, spin: 0, thickness: 0.035, pad: 1.4 },
        { shape: "lock", color: 0x342c4c, azimuth: -1.5, elevation: 0.1, lift: 0, width: 0.1, length: 0.34, taper: 0.3, skew: 0, bend: 0, pitch: 0, spin: 0, thickness: 0.035, pad: 1.4, note: "长鬓发" },
        { shape: "lock", color: 0x342c4c, azimuth: 1.5, elevation: 0.12, lift: 0, width: 0.09, length: 0.2, taper: 0.35, skew: 0, bend: 0, pitch: 0, spin: 0, thickness: 0.035, pad: 1.4, note: "短鬓发" },
      ],
    },
    spawn: { x: 0.3, z: 0.4 },
  },
  {
    id: "sinclair",
    displayName: "Sinclair",
    // Appearance only — lore/weapons/home: docs/DESIGN.md (SMG; ops table studious).
    // Shortest of the three, and the only one with goggles. The hair is a full
    // leaf-shaped mass built strand by strand in the tuner rather than a fringe
    // formula, so it stays a literal list.
    spec: {
      scale: 0.93,
      headRadius: 0.245,
      bodyHeight: 0.55,
      // Kept from the tuner session, which predates the toon ramp: these were
      // chosen when every facet had its own brightness. Under the ramp a head
      // this coarse reads as dented — raise toward the 16/12 default if it
      // bothers you.
      headSegments: 9,
      headRings: 6,
      capDepth: 1.05,
      backDepth: 1.95,
      faceGap: 1.55,
      tailLength: 0,
      handRadius: 0.07,
      skin: 0xf3e0cd,
      hair: 0xd9b96a,
      hairShade: 0xbd9a4e,
      hairTie: 0xbd9a4e,
      body: 0x5f5f4a,
      accent: 0x5a606b,
      gogglesColor: 0xa25353,
      goggles: true,
      pieces: [
        { shape: "disc", color: 0xb4b45a, azimuth: 0.34, elevation: -0.02, lift: 0.004, width: 0.08, length: 0.09, taper: 0.7, skew: 0, bend: 0, pitch: 0, spin: 0, thickness: 0.012, pad: 1.4, note: "眼睛" },
        { shape: "disc", color: 0xb4b45a, azimuth: -0.34, elevation: 0.02, lift: 0.004, width: 0.08, length: 0.09, taper: 0.7, skew: 0, bend: 0, pitch: 0, spin: 0, thickness: 0.012, pad: 1.4, note: "眼睛" },
        { shape: "disc", color: 0xd9a97f, azimuth: 0.74, elevation: -0.3, lift: 0.003, width: 0.07, length: 0.045, taper: 0.7, skew: 0, bend: 0, pitch: 0, spin: 0, thickness: 0.01, pad: 1.4, note: "腮红" },
        { shape: "disc", color: 0xd9a97f, azimuth: -0.74, elevation: -0.3, lift: 0.003, width: 0.07, length: 0.045, taper: 0.7, skew: 0, bend: 0, pitch: 0, spin: 0, thickness: 0.01, pad: 1.4, note: "腮红" },
        { shape: "leaf", color: 0xd9b96a, azimuth: 0, elevation: 0.72, lift: 0, width: 0.16, length: 0.23, taper: 0.7, skew: 0, bend: 0.18, pitch: -0.4, spin: 0, thickness: 0.046, pad: 1.4 },
        { shape: "leaf", color: 0xd9b96a, azimuth: 0.498, elevation: 0.72, lift: 0, width: 0.16, length: 0.22, taper: 0.7, skew: 0.07, bend: 0.18, pitch: -0.4, spin: 0, thickness: 0.046, pad: 1.4 },
        { shape: "leaf", color: 0xd9b96a, azimuth: 0.498, elevation: 0.72, lift: 0, width: 0.16, length: 0.22, taper: 0.7, skew: 0.07, bend: 0.18, pitch: -0.4, spin: 0, thickness: 0.046, pad: 1.4 },
        { shape: "leaf", color: 0xd9b96a, azimuth: -0.498, elevation: 0.72, lift: 0, width: 0.16, length: 0.22, taper: 0.7, skew: -0.07, bend: -0.18, pitch: -0.4, spin: 0, thickness: 0.046, pad: 1.4 },
        { shape: "leaf", color: 0xd9b96a, azimuth: 0, elevation: 0.8, lift: 0, width: 0.16, length: 0.22, taper: 0.7, skew: -0.095, bend: 0.18, pitch: -0.4, spin: 0, thickness: 0.046, pad: 1.4 },
        { shape: "lock", color: 0xd9b96a, azimuth: 1.098, elevation: 0.3, lift: 0, width: 0.115, length: 0.26, taper: 0.7, skew: -0.04, bend: 0, pitch: -0.26, spin: 0, thickness: 0.035, pad: 1.4 },
        { shape: "lock", color: 0xd9b96a, azimuth: 1.098, elevation: 0.3, lift: 0, width: 0.115, length: 0.26, taper: 0.7, skew: -0.04, bend: 0, pitch: -0.26, spin: 0, thickness: 0.035, pad: 1.4 },
        { shape: "lock", color: 0xd9b96a, azimuth: -1.098, elevation: 0.3, lift: 0, width: 0.115, length: 0.26, taper: 0.7, skew: 0.04, bend: 0, pitch: -0.26, spin: 0, thickness: 0.035, pad: 1.4 },
        { shape: "leaf", color: 0xd9b96a, azimuth: 1.678, elevation: 0.3, lift: -0.018, width: 0.19, length: 0.275, taper: 0.7, skew: 0, bend: 0, pitch: -0.32, spin: 0, thickness: 0.035, pad: 1.4 },
        { shape: "leaf", color: 0xd9b96a, azimuth: 1.678, elevation: 0.3, lift: -0.018, width: 0.19, length: 0.275, taper: 0.7, skew: 0, bend: 0, pitch: -0.32, spin: 0, thickness: 0.035, pad: 1.4 },
        { shape: "leaf", color: 0xd9b96a, azimuth: -1.678, elevation: 0.3, lift: -0.018, width: 0.19, length: 0.275, taper: 0.7, skew: 0, bend: 0, pitch: -0.32, spin: 0, thickness: 0.035, pad: 1.4 },
        { shape: "leaf", color: 0xd9b96a, azimuth: -2.082, elevation: 0.3, lift: -0.018, width: 0.19, length: 0.305, taper: 0.7, skew: 0, bend: 0, pitch: -0.4, spin: 0, thickness: 0.035, pad: 1.4 },
        { shape: "leaf", color: 0xd9b96a, azimuth: -2.082, elevation: 0.3, lift: -0.018, width: 0.19, length: 0.305, taper: 0.7, skew: 0, bend: 0, pitch: -0.4, spin: 0, thickness: 0.035, pad: 1.4 },
        { shape: "leaf", color: 0xd9b96a, azimuth: 2.082, elevation: 0.3, lift: -0.018, width: 0.19, length: 0.305, taper: 0.7, skew: 0, bend: 0, pitch: -0.4, spin: 0, thickness: 0.035, pad: 1.4 },
        { shape: "leaf", color: 0xd9b96a, azimuth: 2.658, elevation: 0.46, lift: -0.018, width: 0.19, length: 0.34, taper: 0.7, skew: 0, bend: 0, pitch: -0.4, spin: 0, thickness: 0.035, pad: 1.4 },
        { shape: "leaf", color: 0xd9b96a, azimuth: -2.658, elevation: 0.46, lift: -0.018, width: 0.19, length: 0.34, taper: 0.7, skew: 0, bend: 0, pitch: -0.4, spin: 0, thickness: 0.035, pad: 1.4 },
        { shape: "leaf", color: 0xd9b96a, azimuth: -3.142, elevation: 0.46, lift: -0.018, width: 0.205, length: 0.375, taper: 0.7, skew: 0, bend: 0, pitch: -0.4, spin: 0, thickness: 0.035, pad: 1.4 },
      ],
    },
    spawn: { x: 2.1, z: 1.5 },
  },
];
